# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2026, UAB Kurokesu. All rights reserved.
#
# Dummy DKMS module used by selftest.yml on the main branch. Not for
# installation.

PACKAGE_NAME="kurokesu-selftest-dkms"
PACKAGE_VERSION="1.0.0"

BUILT_MODULE_NAME="selftest"
DEST_MODULE_LOCATION="/updates"

MAKE="make module KDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"

AUTOINSTALL="yes"
